/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAccessRouteImport } from './routes/dashboard/access'
import { Route as DashboardCliRouteImport } from './routes/dashboard/cli'
import { Route as DashboardTunnelsRouteImport } from './routes/dashboard/tunnels'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccessRoute = DashboardAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCliRoute = DashboardCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTunnelsRoute = DashboardTunnelsRouteImport.update({
  id: '/tunnels',
  path: '/tunnels',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/cli': typeof DashboardCliRoute
  '/dashboard/tunnels': typeof DashboardTunnelsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/cli': typeof DashboardCliRoute
  '/dashboard/tunnels': typeof DashboardTunnelsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/device': typeof DeviceRoute
  '/login': typeof LoginRoute
  '/dashboard/access': typeof DashboardAccessRoute
  '/dashboard/cli': typeof DashboardCliRoute
  '/dashboard/tunnels': typeof DashboardTunnelsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/device'
    | '/login'
    | '/dashboard/access'
    | '/dashboard/cli'
    | '/dashboard/tunnels'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/device'
    | '/login'
    | '/dashboard/access'
    | '/dashboard/cli'
    | '/dashboard/tunnels'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/device'
    | '/login'
    | '/dashboard/access'
    | '/dashboard/cli'
    | '/dashboard/tunnels'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeviceRoute: typeof DeviceRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/access': {
      id: '/dashboard/access'
      path: '/access'
      fullPath: '/dashboard/access'
      preLoaderRoute: typeof DashboardAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cli': {
      id: '/dashboard/cli'
      path: '/cli'
      fullPath: '/dashboard/cli'
      preLoaderRoute: typeof DashboardCliRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tunnels': {
      id: '/dashboard/tunnels'
      path: '/tunnels'
      fullPath: '/dashboard/tunnels'
      preLoaderRoute: typeof DashboardTunnelsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccessRoute: typeof DashboardAccessRoute
  DashboardCliRoute: typeof DashboardCliRoute
  DashboardTunnelsRoute: typeof DashboardTunnelsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccessRoute: DashboardAccessRoute,
  DashboardCliRoute: DashboardCliRoute,
  DashboardTunnelsRoute: DashboardTunnelsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeviceRoute: DeviceRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
